#! /bin/sh

sxhkd &
#Configurando LAS PANTALLAS MULTIPLES
xrandr --output eDP-1 --mode 1366x768 --rotate normal --output DP-1 --off --output HDMI-1 --off --output HDMI-2 --primary --mode 1920x1080i --left-of eDP-1 --rotate normal &
#Configurando Transparencias de utilidades (procesos del sistema que ejecutemos)
compton --config ~/.config/compton/compton.conf &
#Arreglo para JAVA
wmname LG3D &
#Seteando FONDO DE ESCRITORIO
feh --bg-fill ~/.config/bspwm/culturagreen.jpg &

~/.config/polybar/launch.sh &
#Iniciando Power manager para poder controlar el SUSPENDIDO y acciones de tapa del pc
mate-power-manager &
#Iniciando
nm-applet &

#Seteamos la tecla WINDOWS(mod1) como PREFIX 
bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a not3CRUD-not3CRUD desktop='^8' state=floating follow=on
bspc rule -a Caja desktop='^8' state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating

