#! /bin/sh

##Eliminando las reglas existentes
bspc rule -r "*"
killall "nm-applet" &
killall "polybar" &

#Configurando LAS PANTALLAS MULTIPLES

hdmi_monitor=$(xrandr --listactivemonitors | awk "/HDMI-2/" | awk '{print $4}')
edp_monitor=$(xrandr --listactivemonitors | awk "/eDP-1/" | awk '{print $4}')

if [ -n "$hdmi_monitor" ] && [ -n "$edp_monitor" ]; then
    xrandr --output HDMI-2 --primary --auto --left-of eDP-1 --rotate normal --output eDP-1 --auto --rotate normal &
fi

sleep 3 &

#Iniciando SXHKD (Controla los atajos del teclado)
sxhkd &

#Configurando Transparencias de utilidades (procesos del sistema que ejecutemos)
#He deshabilitado las transparencias
#  compton --config ~/.config/compton/compton.conf &

#Arreglo para JAVA
wmname LG3D &

#Seteando FONDO DE ESCRITORIO
#feh --bg-scale --no-fehbg ~/Imágenes/culturagreen.jpg &
feh --bg-fill ~/Logo_Azanet.png &

#Iniciando Polybar
~/.config/polybar/launch.sh &

#SETEANDO LAS POLIBARs Según los monitores existentes

if [ -n "$hdmi_monitor" ] && [ -n "$edp_monitor" ]; then
    bspc monitor HDMI-2 -d I II III IV V VI VII
    bspc monitor eDP-1 -d VIII IX X XII
else
    if [ -n "$hdmi_monitor" ]; then
        bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X XI
    fi

    if [ -n "$edp_monitor" ]; then
        bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X XI
    fi
fi




#Iniciando Power manager para poder controlar el SUSPENDIDO y acciones de tapa del pc
mate-power-manager &
#Iniciamos NetworkManager, para acceder por la barra de tareas a la configuración de red
nm-applet &

#Seteamos la tecla WINDOWS(mod1) como PREFIX
bspc config pointer_modifier mod1


bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

##CONFIGuraciones en modo de pruebas
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true 

bspc config normal_border_color     "#454747"
bspc config active_border_color     "#74c2c2"
bspc config focused_border_color    "#bfff00"
bspc config presel_border_color     "#74c2c2"
bspc config urgent_border_color     "#74c2c2"




#bspc rule -a not3CRUD-not3CRUD state=floating follow=on
#bspc rule -a Caja state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium  desktoo='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating

